/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GiveDirectly.DonorRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.GiveDirectlyEnterprise;
import Business.Organization.GiveDirectly.DonorOrganization;
import Business.Person.Donor;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Amey
 */
public class DonorWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private DonorOrganization donorOrganization;
    private UserAccount userAccount;
    private Enterprise enterprise;
    /**
     * Creates new form DonorWorkAreAJPanel
     */
    public DonorWorkAreaJPanel(JPanel userJPanel, Enterprise enterprise, 
            DonorOrganization organization,UserAccount account) {
        initComponents();
        this.userProcessContainer = userJPanel;
        this.enterprise = enterprise;
        this.donorOrganization = organization;
        this.userAccount = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donorWorkAreaJLabel = new javax.swing.JLabel();
        makeDonationJButton = new javax.swing.JButton();
        viewDonationHistoryJButton = new javax.swing.JButton();

        donorWorkAreaJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        donorWorkAreaJLabel.setText("My Work Area - Donor Role");

        makeDonationJButton.setText("Make Donation");
        makeDonationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeDonationJButtonActionPerformed(evt);
            }
        });

        viewDonationHistoryJButton.setText("View Donation History");
        viewDonationHistoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDonationHistoryJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(donorWorkAreaJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(viewDonationHistoryJButton)
                            .addComponent(makeDonationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(donorWorkAreaJLabel)
                .addGap(51, 51, 51)
                .addComponent(makeDonationJButton)
                .addGap(49, 49, 49)
                .addComponent(viewDonationHistoryJButton)
                .addContainerGap(361, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void makeDonationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeDonationJButtonActionPerformed
        try {
            // TODO add your handling code here:
            //Donor donor = (Donor)userAccount.getPerson();
            MakeDonationJPanel makeDonationJPanel = new MakeDonationJPanel(userProcessContainer,(GiveDirectlyEnterprise)enterprise,userAccount);
            userProcessContainer.add("MakeDonationJPanel", makeDonationJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } catch (ParseException ex) {
            Logger.getLogger(DonorWorkAreaJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_makeDonationJButtonActionPerformed

    private void viewDonationHistoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDonationHistoryJButtonActionPerformed
        // TODO add your handling code here:
        ViewDonationHistoryJPanel viewDonationHistoryJPanel = new ViewDonationHistoryJPanel(
                userProcessContainer,(GiveDirectlyEnterprise)enterprise,(Donor)userAccount.getPerson());
        userProcessContainer.add("ViewDonationHistoryJPanel", viewDonationHistoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewDonationHistoryJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel donorWorkAreaJLabel;
    private javax.swing.JButton makeDonationJButton;
    private javax.swing.JButton viewDonationHistoryJButton;
    // End of variables declaration//GEN-END:variables
}
