/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GiveDirectly.DonorRole;

import Business.Enterprise.GiveDirectlyEnterprise;
import Business.GiveDirectly.FinanceAccount;
import Business.Person.Donor;
import Business.Transaction.Transaction;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Amey
 */
public class MakeDonationJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private GiveDirectlyEnterprise giveDirectlyEnterprise;
    private UserAccount userAccount;
    
    /**
     * Creates new form MakeDonationJPanel
     */
    public MakeDonationJPanel(JPanel userJPanel,GiveDirectlyEnterprise enterprise,UserAccount account) throws ParseException {
        initComponents();
        this.userProcessContainer = userJPanel;
        this.giveDirectlyEnterprise = enterprise;
        this.userAccount = account;
        ((JTextField)expiryDateJDateChooser.getDateEditor().getUiComponent()).setEnabled(false);
        expiryDateJDateChooser.getJCalendar().setSelectableDateRange(new Date(),new SimpleDateFormat("dd-MMM-yyyy").parse("31-Dec-2099"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardTypeJbuttonGroup = new javax.swing.ButtonGroup();
        makeDonationJLabel = new javax.swing.JLabel();
        amountJLabel = new javax.swing.JLabel();
        cardTypeJLabel = new javax.swing.JLabel();
        cardNumberJLabel = new javax.swing.JLabel();
        cvvJLabel = new javax.swing.JLabel();
        expiryDateJLabel = new javax.swing.JLabel();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        expiryDateJDateChooser = new com.toedter.calendar.JDateChooser();
        amountJTextField = new javax.swing.JTextField();
        cardNumberJTextField1 = new javax.swing.JTextField();
        cardNumberJTextField2 = new javax.swing.JTextField();
        cardNumberJTextField3 = new javax.swing.JTextField();
        cardNumberJTextField4 = new javax.swing.JTextField();
        cvvJTextField = new javax.swing.JTextField();
        visaCardJRadioButton = new javax.swing.JRadioButton();
        masterCardJRadioButton = new javax.swing.JRadioButton();
        americanExpressJRadioButton = new javax.swing.JRadioButton();

        makeDonationJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        makeDonationJLabel.setText("Make Donation");

        amountJLabel.setText("Enter Amount");

        cardTypeJLabel.setText("Card Type");

        cardNumberJLabel.setText("Card Number");

        cvvJLabel.setText("CVV");

        expiryDateJLabel.setText("Expiry Date");

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        expiryDateJDateChooser.setDateFormatString("dd-MMM-yyyy");
        expiryDateJDateChooser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                expiryDateJDateChooserKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                expiryDateJDateChooserKeyTyped(evt);
            }
        });

        amountJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountJTextFieldActionPerformed(evt);
            }
        });
        amountJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                amountJTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountJTextFieldKeyTyped(evt);
            }
        });

        cardNumberJTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cardNumberJTextField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cardNumberJTextField1KeyTyped(evt);
            }
        });

        cardNumberJTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cardNumberJTextField2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cardNumberJTextField2KeyTyped(evt);
            }
        });

        cardNumberJTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberJTextField3ActionPerformed(evt);
            }
        });
        cardNumberJTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cardNumberJTextField3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cardNumberJTextField3KeyTyped(evt);
            }
        });

        cardNumberJTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberJTextField4ActionPerformed(evt);
            }
        });
        cardNumberJTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cardNumberJTextField4KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cardNumberJTextField4KeyTyped(evt);
            }
        });

        cvvJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvJTextFieldActionPerformed(evt);
            }
        });
        cvvJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cvvJTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cvvJTextFieldKeyTyped(evt);
            }
        });

        cardTypeJbuttonGroup.add(visaCardJRadioButton);
        visaCardJRadioButton.setText("Visa Card");

        cardTypeJbuttonGroup.add(masterCardJRadioButton);
        masterCardJRadioButton.setText("Master Card");

        cardTypeJbuttonGroup.add(americanExpressJRadioButton);
        americanExpressJRadioButton.setText("Americn Express");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardTypeJLabel)
                    .addComponent(amountJLabel)
                    .addComponent(cardNumberJLabel)
                    .addComponent(cvvJLabel)
                    .addComponent(expiryDateJLabel))
                .addGap(210, 210, 210)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(expiryDateJDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(amountJTextField)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(cardNumberJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(cardNumberJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(13, 13, 13)
                            .addComponent(cardNumberJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cardNumberJTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cvvJTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(visaCardJRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(masterCardJRadioButton)
                        .addGap(31, 31, 31)
                        .addComponent(americanExpressJRadioButton)))
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(makeDonationJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(backJButton)
                        .addGap(72, 72, 72)
                        .addComponent(submitJButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(makeDonationJLabel)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountJLabel)
                    .addComponent(amountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardTypeJLabel)
                    .addComponent(visaCardJRadioButton)
                    .addComponent(masterCardJRadioButton)
                    .addComponent(americanExpressJRadioButton))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNumberJLabel)
                    .addComponent(cardNumberJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNumberJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNumberJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNumberJTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvvJLabel)
                    .addComponent(cvvJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expiryDateJLabel)
                    .addComponent(expiryDateJDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(submitJButton))
                .addContainerGap(145, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        // TODO add your handling code here:
        if (amountJTextField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the amount you wish to donate!!!");
            amountJTextField.setText("");
            amountJTextField.requestFocus();
        }
        else if((visaCardJRadioButton.isSelected() == false) &&(masterCardJRadioButton.isSelected() == false)
                &&(americanExpressJRadioButton.isSelected() == false)){
            JOptionPane.showMessageDialog(null, "Please select a card Type!!!");
        }
        else if (cardNumberJTextField1.getText().trim().equals("")
                || cardNumberJTextField2.getText().trim().equals("")
                || cardNumberJTextField3.getText().trim().equals("")
                || cardNumberJTextField4.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the correct Card Number!!!");
            cardNumberJTextField1.setText("");
            cardNumberJTextField2.setText("");
            cardNumberJTextField3.setText("");
            cardNumberJTextField4.setText("");
            cardNumberJTextField1.requestFocus();
        }
        else if (cardNumberJTextField1.getText().length() < 4
                || cardNumberJTextField2.getText().length() < 4
                || cardNumberJTextField3.getText().length() < 4
                || cardNumberJTextField4.getText().length() < 4) {
            JOptionPane.showMessageDialog(null, "Please enter the correct Card Number!!!");
            cardNumberJTextField1.setText("");
            cardNumberJTextField2.setText("");
            cardNumberJTextField3.setText("");
            cardNumberJTextField4.setText("");
            cardNumberJTextField1.requestFocus();
        }
        else if (cvvJTextField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the CVV!!!");
            cvvJTextField.setText("");
            cvvJTextField.requestFocus();
        }
        else if (cvvJTextField.getText().length() <3) {
            JOptionPane.showMessageDialog(null, "Please enter the correct CVV!!!");
            cvvJTextField.setText("");
            cvvJTextField.requestFocus();
        }
        else if (((JTextField)expiryDateJDateChooser.getDateEditor().getUiComponent()).getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the expiry date!!!");
            expiryDateJDateChooser.requestFocus();
        }
        else if (Float.parseFloat(amountJTextField.getText()) > 500000){
            JOptionPane.showMessageDialog(null, "You can only donate $5,00,000 at a time!!!");
            amountJTextField.setText("");
            amountJTextField.requestFocus();
        }
        else{
            try{
                FinanceAccount financeAccount = FinanceAccount.getInstance();
    //            float sumTotal = financeAccount.getBalanceAmount();
                float amountDonated = 
                        Float.parseFloat(amountJTextField.getText());
    //            financeAccount.setBalanceAmount(sumTotal+amountDonated);
                financeAccount.setTimestamp(new Date());

                financeAccount.updateDirectory(amountDonated,userAccount, null);

                Transaction transaction = giveDirectlyEnterprise.
                        getTransactionDirectory().addTransaction();
                transaction.setSender((Donor)userAccount.getPerson());
                transaction.setAmount(amountDonated);
                transaction.setReceiver("GiveDirectly");
                transaction.setTransactionID(transaction.getTransactionID());
                transaction.setTimeStamp(new Date());
                System.out.println(financeAccount.getBalanceAmount());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,
                        "Please insert valid number value!!!");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,
                        "There's some error with database,please try again later!!");
            }
        }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void amountJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountJTextFieldActionPerformed

    private void cardNumberJTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberJTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumberJTextField3ActionPerformed

    private void cardNumberJTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberJTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumberJTextField4ActionPerformed

    private void cardNumberJTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNumberJTextField1KeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        int length = cardNumberJTextField1.getText().length();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)
                || length >= 4){
            getToolkit().beep();
            evt.consume();
        }
        if (length < 4) {
            cardNumberJTextField1.requestFocus();
        }
        else{
            cardNumberJTextField1.transferFocus();
        }
      

    }//GEN-LAST:event_cardNumberJTextField1KeyTyped

    private void cardNumberJTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNumberJTextField2KeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        int length = cardNumberJTextField2.getText().length();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)
                || length >= 4){
            getToolkit().beep();
            evt.consume();
        }
        if (length < 4) {
            cardNumberJTextField2.requestFocus();
        }
        else{
            cardNumberJTextField2.transferFocus();
        }
    }//GEN-LAST:event_cardNumberJTextField2KeyTyped

    private void cardNumberJTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNumberJTextField3KeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        int length = cardNumberJTextField3.getText().length();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)
                || length >= 4){
            getToolkit().beep();
            evt.consume();
        }
        if (length < 4) {
            cardNumberJTextField3.requestFocus();
        }
        else{
            cardNumberJTextField3.transferFocus();
        }
    }//GEN-LAST:event_cardNumberJTextField3KeyTyped

    private void cardNumberJTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNumberJTextField4KeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        int length = cardNumberJTextField4.getText().length();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)
                || length >= 4){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_cardNumberJTextField4KeyTyped

    private void amountJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountJTextFieldKeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_amountJTextFieldKeyTyped

    private void cvvJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvJTextFieldActionPerformed

    private void cvvJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvvJTextFieldKeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        int length = cvvJTextField.getText().length();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)
                || length >= 3){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_cvvJTextFieldKeyTyped

    private void expiryDateJDateChooserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expiryDateJDateChooserKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiryDateJDateChooserKeyPressed

    private void expiryDateJDateChooserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expiryDateJDateChooserKeyTyped
        // TODO add your handling code here:
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            Date date = (Date) evt.getSource();
//            SimpleDateFormat formatter = new SimpleDateFormat("dd-MMM-yyyy");
//            String dateString = formatter.format(date);
//            if(!(date.equals(dateString)))
//            {
//                evt.consume();
//                JOptionPane.showMessageDialog(null, "Please enter correct date");
//            }
//        }
    }//GEN-LAST:event_expiryDateJDateChooserKeyTyped

    private void amountJTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountJTextFieldKeyPressed
        // TODO add your handling code here:
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_C) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot copy code from this field!!!");
        } 
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_X) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot cut code from this field!!!");
        } 
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_V) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot paste code into this field!!!");
        }
    }//GEN-LAST:event_amountJTextFieldKeyPressed

    private void cardNumberJTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNumberJTextField1KeyPressed
        // TODO add your handling code here:
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_C) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot copy code from this field!!!");
        } 
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_X) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot cut code from this field!!!");
        } 
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_V) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot paste code into this field!!!");
        }
    }//GEN-LAST:event_cardNumberJTextField1KeyPressed

    private void cardNumberJTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNumberJTextField2KeyPressed
        // TODO add your handling code here:
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_C) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot copy code from this field!!!");
        } 
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_X) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot cut code from this field!!!");
        } 
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_V) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot paste code into this field!!!");
        }
    }//GEN-LAST:event_cardNumberJTextField2KeyPressed

    private void cardNumberJTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNumberJTextField3KeyPressed
        // TODO add your handling code here:
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_C) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot copy code from this field!!!");
        } 
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_X) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot cut code from this field!!!");
        } 
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_V) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot paste code into this field!!!");
        }
    }//GEN-LAST:event_cardNumberJTextField3KeyPressed

    private void cardNumberJTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNumberJTextField4KeyPressed
        // TODO add your handling code here:
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_C) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot copy code from this field!!!");
        } 
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_X) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot cut code from this field!!!");
        } 
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_V) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot paste code into this field!!!");
        }
    }//GEN-LAST:event_cardNumberJTextField4KeyPressed

    private void cvvJTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvvJTextFieldKeyPressed
        // TODO add your handling code here:
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_C) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot copy code from this field!!!");
        } 
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_X) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot cut code from this field!!!");
        } 
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_V) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot paste code into this field!!!");
        }
    }//GEN-LAST:event_cvvJTextFieldKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton americanExpressJRadioButton;
    private javax.swing.JLabel amountJLabel;
    private javax.swing.JTextField amountJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel cardNumberJLabel;
    private javax.swing.JTextField cardNumberJTextField1;
    private javax.swing.JTextField cardNumberJTextField2;
    private javax.swing.JTextField cardNumberJTextField3;
    private javax.swing.JTextField cardNumberJTextField4;
    private javax.swing.JLabel cardTypeJLabel;
    private javax.swing.ButtonGroup cardTypeJbuttonGroup;
    private javax.swing.JLabel cvvJLabel;
    private javax.swing.JTextField cvvJTextField;
    private com.toedter.calendar.JDateChooser expiryDateJDateChooser;
    private javax.swing.JLabel expiryDateJLabel;
    private javax.swing.JLabel makeDonationJLabel;
    private javax.swing.JRadioButton masterCardJRadioButton;
    private javax.swing.JButton submitJButton;
    private javax.swing.JRadioButton visaCardJRadioButton;
    // End of variables declaration//GEN-END:variables
}
