/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GiveDirectly.DonorRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Person.Donor;
import Business.Role.DonorRole;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Amey
 */
public class RegisterNewDonorJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Organization organization;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private EcoSystem system;
    private static final String EMAIL_PATTERN = 
    "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
    + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
    /**
     * Creates new form RegisterNewDonorJPanel
     */
    public RegisterNewDonorJPanel(JPanel userJPanel,Organization organization,
            EcoSystem system ) {
        initComponents();
        this.userProcessContainer = userJPanel;
        this.organization = organization; 
        this.system = system;
    }
    
     private boolean isUserNamePresent(String name)
    {
        if(system.getUserAccountDirectory().userNameIsPresent(name)){
            return true;
        }
        for(Network network: system.getNetworkList()){
            System.out.println("Network: "+network);
            for(Enterprise enterprise: network.getEnterpriseDirectory().
                    getEnterpriseList())
            {
                if(enterprise.getUserAccountDirectory().userNameIsPresent(name))
                {
                    return true; 
                }  
                for(Organization org:enterprise.getOrganizationDirectory().
                        getOrganizationList()){
                    if(org.getUserAccountDirectory().userNameIsPresent(name)){
                        return true;
                    }
                }
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        signInJLabel = new javax.swing.JLabel();
        firstNameJLabel = new javax.swing.JLabel();
        lastNameJLabel = new javax.swing.JLabel();
        genderJLabel = new javax.swing.JLabel();
        ageJLabel = new javax.swing.JLabel();
        addressJLabel = new javax.swing.JLabel();
        pincodeJLabel = new javax.swing.JLabel();
        emailIdJLabel = new javax.swing.JLabel();
        phoneNumberJLabel = new javax.swing.JLabel();
        submitJButton = new javax.swing.JButton();
        maleJRadioButton = new javax.swing.JRadioButton();
        femaleJRadioButton = new javax.swing.JRadioButton();
        userNameJLabel = new javax.swing.JLabel();
        passwordJLabel = new javax.swing.JLabel();
        passwordJPasswordField = new javax.swing.JPasswordField();
        userNameJTextField = new javax.swing.JTextField();
        firstNameJTextField = new javax.swing.JTextField();
        lastNameJTextField = new javax.swing.JTextField();
        addressJTextField = new javax.swing.JTextField();
        emailIdJTextField = new javax.swing.JTextField();
        ageJTextField = new javax.swing.JTextField();
        pinCodeJTextField = new javax.swing.JTextField();
        phoneNumberJTextField = new javax.swing.JTextField();

        signInJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        signInJLabel.setText("Donor Sign-In Page");

        firstNameJLabel.setText("First Name");

        lastNameJLabel.setText("Last Name");

        genderJLabel.setText("Gender");

        ageJLabel.setText("Age");

        addressJLabel.setText("Address");

        pincodeJLabel.setText("Pincode");

        emailIdJLabel.setText("Email ID");

        phoneNumberJLabel.setText("Phone Number");

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        genderButtonGroup.add(maleJRadioButton);
        maleJRadioButton.setText("Male");

        genderButtonGroup.add(femaleJRadioButton);
        femaleJRadioButton.setText("Female");

        userNameJLabel.setText("User Name");

        passwordJLabel.setText("Password");

        ageJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageJTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageJTextFieldKeyTyped(evt);
            }
        });

        pinCodeJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pinCodeJTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pinCodeJTextFieldKeyTyped(evt);
            }
        });

        phoneNumberJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneNumberJTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNumberJTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(signInJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastNameJLabel)
                            .addComponent(firstNameJLabel)
                            .addComponent(genderJLabel)
                            .addComponent(ageJLabel)
                            .addComponent(addressJLabel)
                            .addComponent(pincodeJLabel)
                            .addComponent(emailIdJLabel)
                            .addComponent(phoneNumberJLabel)
                            .addComponent(userNameJLabel)
                            .addComponent(passwordJLabel))
                        .addGap(250, 250, 250)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maleJRadioButton)
                                .addGap(51, 51, 51)
                                .addComponent(femaleJRadioButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(phoneNumberJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pinCodeJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ageJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailIdJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addressJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lastNameJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(firstNameJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userNameJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(passwordJPasswordField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(submitJButton)))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(signInJLabel)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameJLabel)
                    .addComponent(firstNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lastNameJLabel)
                    .addComponent(lastNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(genderJLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maleJRadioButton)
                        .addComponent(femaleJRadioButton)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageJLabel)
                    .addComponent(ageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressJLabel)
                    .addComponent(addressJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pincodeJLabel)
                    .addComponent(pinCodeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailIdJLabel)
                    .addComponent(emailIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberJLabel)
                    .addComponent(phoneNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameJLabel)
                    .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordJLabel)
                    .addComponent(passwordJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(submitJButton)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        // TODO add your handling code here:
        if (firstNameJTextField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null,"Please enter the First Name!!");
            firstNameJTextField.setText("");
            firstNameJTextField.requestFocus();
        }
        else if (lastNameJTextField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null,"Please enter the Last Name!!!");
            lastNameJTextField.setText("");
            lastNameJTextField.requestFocus();
        }
        else if((maleJRadioButton.isSelected() == false) &&
                (femaleJRadioButton.isSelected() == false) ){
            JOptionPane.showMessageDialog(null, "Please select the gender!!!");
        } 
        else if (ageJTextField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the Age!!!");
            ageJTextField.setText("");
            ageJTextField.requestFocus();
        }
        else if (addressJTextField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the Address!!!");
            addressJTextField.setText("");
            addressJTextField.requestFocus();
        }
        else if (pinCodeJTextField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the Pin Code!!!");
            pinCodeJTextField.setText("");
            pinCodeJTextField.requestFocus();
        }
        else if (emailIdJTextField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the Email ID!!!");
            emailIdJTextField.setText("");
            emailIdJTextField.requestFocus();
        }
        else if (phoneNumberJTextField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null,"Please enter the Phone !!!");
            phoneNumberJTextField.setText("");
            phoneNumberJTextField.requestFocus();
        }
        else if (userNameJTextField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null,"Please enter the User Name!!!");
            userNameJTextField.setText("");
            userNameJTextField.requestFocus();
        }
        else if (passwordJPasswordField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the Password!!!");
            passwordJPasswordField.setText("");
            passwordJPasswordField.requestFocus();
        }
        else if(!(emailIdJTextField.getText().matches(EMAIL_PATTERN))){
            JOptionPane.showMessageDialog(null, "Please enter valid Email ID!");
            emailIdJTextField.setText("");
            emailIdJTextField.requestFocus();
        }
        else{
            try{
                if(isUserNamePresent(userNameJTextField.getText().trim())){
                    JOptionPane.showMessageDialog(null,"Account Name Already Exists!!");
                    userNameJTextField.setText("");
                    userNameJTextField.requestFocus();
                    return;
                }
         
                String gender = null;
                String firstName = firstNameJTextField.getText().trim();
                String lastName = lastNameJTextField.getText().trim();
                if(maleJRadioButton.isSelected()){
                    gender = "Male";
                }
                else{
                    gender = "Female";
                }
                int age = Integer.parseInt(ageJTextField.getText().trim());
                String address = addressJTextField.getText().trim();
                int pinCode = Integer.parseInt(pinCodeJTextField.getText().trim());
                String emailId = emailIdJTextField.getText().trim();
                float phoneNumber = Float.parseFloat(phoneNumberJTextField.getText());
                String userName = userNameJTextField.getText().trim();
                String password = String.valueOf(passwordJPasswordField.getPassword());
                System.out.println("Current Organization is: "+organization);
                Donor donor = (Donor)organization.getPersonDirectory().createAndAddDonor(firstName,lastName,gender,age,address,phoneNumber,pinCode,emailId);
                        organization.getUserAccountDirectory().createUserAccount(userName, password, donor, new DonorRole());
                JOptionPane.showMessageDialog(null, "Donor successfully registered!!!");

                userProcessContainer.removeAll();
                dB4OUtil.storeSystem(system);
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Please insert valid number value!!!");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "There's some error with database,please try again later!!");
            }
        }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void ageJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageJTextFieldKeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        int length = ageJTextField.getText().length();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)
                || length >= 3){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_ageJTextFieldKeyTyped

    private void pinCodeJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinCodeJTextFieldKeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        int length = pinCodeJTextField.getText().length();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)
                || length>=5){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_pinCodeJTextFieldKeyTyped

    private void phoneNumberJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberJTextFieldKeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        int length = phoneNumberJTextField.getText().length();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)
                || length>=10){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_phoneNumberJTextFieldKeyTyped

    private void ageJTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageJTextFieldKeyPressed
        // TODO add your handling code here:
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_C) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot copy code from this field!!!");
        } 
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_X) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot cut code from this field!!!");
        } 
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_V) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot paste code into this field!!!");
        }
    }//GEN-LAST:event_ageJTextFieldKeyPressed

    private void pinCodeJTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinCodeJTextFieldKeyPressed
        // TODO add your handling code here:
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_C) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot copy code from this field!!!");
        } 
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_X) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot cut code from this field!!!");
        } 
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_V) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot paste code into this field!!!");
        }
    }//GEN-LAST:event_pinCodeJTextFieldKeyPressed

    private void phoneNumberJTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberJTextFieldKeyPressed
        // TODO add your handling code here:
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_C) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot copy code from this field!!!");
        } 
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_X) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot cut code from this field!!!");
        } 
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_V) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot paste code into this field!!!");
        }
    }//GEN-LAST:event_phoneNumberJTextFieldKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressJLabel;
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JLabel ageJLabel;
    private javax.swing.JTextField ageJTextField;
    private javax.swing.JLabel emailIdJLabel;
    private javax.swing.JTextField emailIdJTextField;
    private javax.swing.JRadioButton femaleJRadioButton;
    private javax.swing.JLabel firstNameJLabel;
    private javax.swing.JTextField firstNameJTextField;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel genderJLabel;
    private javax.swing.JLabel lastNameJLabel;
    private javax.swing.JTextField lastNameJTextField;
    private javax.swing.JRadioButton maleJRadioButton;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JLabel phoneNumberJLabel;
    private javax.swing.JTextField phoneNumberJTextField;
    private javax.swing.JTextField pinCodeJTextField;
    private javax.swing.JLabel pincodeJLabel;
    private javax.swing.JLabel signInJLabel;
    private javax.swing.JButton submitJButton;
    private javax.swing.JLabel userNameJLabel;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
