/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GiveDirectly.RecepientRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.GiveDirectly.RecepientOrganization;
import Business.Person.Recepient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Amey
 */
public class RecepientJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private RecepientOrganization recepientOrganization;
    private Enterprise enterprise;
    private EcoSystem system;
    /**
     * Creates new form RecepientJPanel
     */
    public RecepientJPanel(JPanel userJPanel, Enterprise enterprise, 
           RecepientOrganization organization,UserAccount account,EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userJPanel;
        this.enterprise = enterprise;
        this.recepientOrganization = organization;
        this.userAccount = account;
        this.system = ecoSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recepientWorkAreaJLabel = new javax.swing.JLabel();
        requestMoneyJButton = new javax.swing.JButton();
        viewTransactionHistoryJButton = new javax.swing.JButton();
        viewBalanceJButton = new javax.swing.JButton();

        recepientWorkAreaJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        recepientWorkAreaJLabel.setText("Recepient Work Area");

        requestMoneyJButton.setText("Request Money");
        requestMoneyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestMoneyJButtonActionPerformed(evt);
            }
        });

        viewTransactionHistoryJButton.setText("View Transaction History");
        viewTransactionHistoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTransactionHistoryJButtonActionPerformed(evt);
            }
        });

        viewBalanceJButton.setText("View Account Balance");
        viewBalanceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBalanceJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(requestMoneyJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recepientWorkAreaJLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(viewBalanceJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewTransactionHistoryJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(recepientWorkAreaJLabel)
                .addGap(37, 37, 37)
                .addComponent(requestMoneyJButton)
                .addGap(31, 31, 31)
                .addComponent(viewTransactionHistoryJButton)
                .addGap(32, 32, 32)
                .addComponent(viewBalanceJButton)
                .addContainerGap(319, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestMoneyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestMoneyJButtonActionPerformed
        // TODO add your handling code here:
        RequestMoneyJPanel requestMoneyJPanel = new RequestMoneyJPanel(userProcessContainer,
                enterprise,recepientOrganization,userAccount,system);
        userProcessContainer.add("RequestMoneyJPanel", requestMoneyJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestMoneyJButtonActionPerformed

    private void viewTransactionHistoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTransactionHistoryJButtonActionPerformed
        // TODO add your handling code here:
        ViewDonationReceivedHistoryJPanel viewDonationReceivedHistoryJPanel = new ViewDonationReceivedHistoryJPanel(
                userProcessContainer,userAccount,system);
        userProcessContainer.add("ViewMoneyTransactionHistoryJPanel", viewDonationReceivedHistoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewTransactionHistoryJButtonActionPerformed

    private void viewBalanceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBalanceJButtonActionPerformed
        // TODO add your handling code here:
        ViewAcctBalanceJPanel viewAcctBalanceJPanel = new ViewAcctBalanceJPanel(userProcessContainer,(Recepient)userAccount.getPerson());
        userProcessContainer.add("ViewMoneyTransactionHistoryJPanel", viewAcctBalanceJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewBalanceJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel recepientWorkAreaJLabel;
    private javax.swing.JButton requestMoneyJButton;
    private javax.swing.JButton viewBalanceJButton;
    private javax.swing.JButton viewTransactionHistoryJButton;
    // End of variables declaration//GEN-END:variables
}
