/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GiveDirectly.IdentificationTeamRole;

import Business.Enterprise.Enterprise;
import Business.Government.CensusData;
import Business.Organization.GiveDirectly.RecepientOrganization;
import Business.Organization.Organization;
import Business.Person.Recepient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CensusDataWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amey
 */
public class ViewDataJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private CensusDataWorkRequest censusDataWorkRequest;
    
    /**
     * Creates new form ViewDataJPanel
     */
    public ViewDataJPanel(JPanel userJPanel,UserAccount account,Enterprise enterprise,CensusDataWorkRequest request) {
        initComponents();
        this.userProcessContainer = userJPanel;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.censusDataWorkRequest = request;
        populateCensusData();
    }
    private void populateCensusData(){
        DefaultTableModel model = (DefaultTableModel)censusDataJTable.getModel();
        model.setRowCount(0);
         
//        for(WorkRequest workRequest:userAccount.getWorkQueue().getWorkRequestList()){
//            Date tempDate= workRequest.getRequestDate();
//                if(censusDataWorkRequest.getRequestDate().equals(tempDate)){
                for(CensusData censusData : censusDataWorkRequest.getCensusDataDirectory().getCensusDataList()){
                    Object[] object = new Object[7];
                    object[0] = censusData.getFirstName();
                    object[1] = censusData.getLastName();
                    object[2] = censusData.getNationalID();
                    object[3] = censusData.getCountry();
                    object[4] = censusData.getRegion();
                    object[5] = censusData.getAddress();
                    object[6] = censusData.getIncomeAnually();
                    model.addRow(object); 
                }     
//            }
//        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        censusDataJTable = new javax.swing.JTable();
        filteredDataJLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        filteredCensusDataJTable1 = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        filterRecordJButton = new javax.swing.JButton();
        governmentDataJLabel = new javax.swing.JLabel();

        censusDataJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "National ID", "Country", "Region", "Address", "Income"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(censusDataJTable);

        filteredDataJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        filteredDataJLabel.setText("GiveDirectly Filtered Record");

        filteredCensusDataJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "National ID", "Country", "Region", "Address", "Income"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(filteredCensusDataJTable1);

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        filterRecordJButton.setText("Filter Record");
        filterRecordJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterRecordJButtonActionPerformed(evt);
            }
        });

        governmentDataJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        governmentDataJLabel.setText("Government Census Record");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(filterRecordJButton)
                .addGap(466, 466, 466))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filteredDataJLabel)
                    .addComponent(backJButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(governmentDataJLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(governmentDataJLabel)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(filterRecordJButton)
                .addGap(49, 49, 49)
                .addComponent(filteredDataJLabel)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(backJButton)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void filterRecordJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterRecordJButtonActionPerformed
        // TODO add your handling code here:
        Organization organization = null;
        DefaultTableModel model = (DefaultTableModel)filteredCensusDataJTable1.getModel();
        model.setRowCount(0);
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(org instanceof RecepientOrganization)
                 organization = org;
        }
        for(CensusData censusData : censusDataWorkRequest.getCensusDataDirectory().getCensusDataList()){
            if(censusData.getIncomeAnually()< 250){
                System.out.println("organization"+organization);
                Recepient recepient = (Recepient) organization.getPersonDirectory().createAndAddRecipient(censusData.getFirstName(), 
                               censusData.getLastName(), null,0, censusData.getAddress(), 0, 0, 0, 0, 0, 
                               null, censusData.getNationalID(),censusData.getRegion(),
                               censusData.getCountry(),censusData.getIncomeAnually());
                        
                Object[] object = new Object[7];
                object[0] = censusData.getFirstName();
                object[1] = censusData.getLastName();
                object[2] = censusData.getNationalID();
                object[3] = censusData.getCountry();
                object[4] = censusData.getRegion();
                object[5] = censusData.getAddress();
                object[6] = censusData.getIncomeAnually();
                model.addRow(object);
            }
        }
        JOptionPane.showMessageDialog(null,"Data Filtered successfully!!");
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_filterRecordJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTable censusDataJTable;
    private javax.swing.JButton filterRecordJButton;
    private javax.swing.JTable filteredCensusDataJTable1;
    private javax.swing.JLabel filteredDataJLabel;
    private javax.swing.JLabel governmentDataJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
