/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.MobileMoneyTransfer.VendorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.MobileMoneyTransfer.VendorOrganization;
import Business.Person.Vendor;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Amey
 */
public class VendorJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private VendorOrganization vendorOrganization;
    private Enterprise enterprise;
    private EcoSystem system;
    /**
     * Creates new form VendorJPanel
     */
    public VendorJPanel(JPanel userJPanel, Enterprise enterprise, 
           VendorOrganization organization,UserAccount account,EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userJPanel;
        this.enterprise = enterprise;
        this.vendorOrganization = organization;
        this.userAccount = account;
        this.system = ecoSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vendorWorkAreaJLabel = new javax.swing.JLabel();
        provideMoneyJButton = new javax.swing.JButton();
        viewMoneyProvisionHistoryJButton = new javax.swing.JButton();

        vendorWorkAreaJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        vendorWorkAreaJLabel.setText("Vendor Work Area");

        provideMoneyJButton.setText("Provide Money");
        provideMoneyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provideMoneyJButtonActionPerformed(evt);
            }
        });

        viewMoneyProvisionHistoryJButton.setText("View Provision History");
        viewMoneyProvisionHistoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMoneyProvisionHistoryJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(375, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(provideMoneyJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vendorWorkAreaJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewMoneyProvisionHistoryJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(351, 351, 351))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(vendorWorkAreaJLabel)
                .addGap(35, 35, 35)
                .addComponent(provideMoneyJButton)
                .addGap(35, 35, 35)
                .addComponent(viewMoneyProvisionHistoryJButton)
                .addContainerGap(357, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void provideMoneyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provideMoneyJButtonActionPerformed
        // TODO add your handling code here:
        ProvideMoneyJPanel provideMoneyJPanel = new ProvideMoneyJPanel(userProcessContainer,
                enterprise,vendorOrganization,userAccount,system);
        userProcessContainer.add("ProvideMoneyJPanel", provideMoneyJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_provideMoneyJButtonActionPerformed

    private void viewMoneyProvisionHistoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMoneyProvisionHistoryJButtonActionPerformed
        // TODO add your handling code here:
        ViewProvisionHistoryJPanel viewProvisionHistoryJPanel = new ViewProvisionHistoryJPanel(
                userProcessContainer,userAccount,system);
        userProcessContainer.add("ProvideMoneyJPanel", viewProvisionHistoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewMoneyProvisionHistoryJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton provideMoneyJButton;
    private javax.swing.JLabel vendorWorkAreaJLabel;
    private javax.swing.JButton viewMoneyProvisionHistoryJButton;
    // End of variables declaration//GEN-END:variables
}
