/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GiveDirectly.FinanceTeamRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.GiveDirectlyEnterprise;
import Business.Organization.Organization;
import Business.Transaction.TransactionDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Amey
 */
public class FinanceTeamJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Organization organization;
    private EcoSystem system;
    /**
     * Creates new form FinanceTeamJPanel
     */
    public FinanceTeamJPanel(JPanel userJPanel, Enterprise enterprise, 
            Organization organization,UserAccount account,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userJPanel;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = account;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        financeTeamWorkAreaJLabel = new javax.swing.JLabel();
        requestAccountJButton = new javax.swing.JButton();
        transferAmountJButton = new javax.swing.JButton();
        viewDonationsJButton = new javax.swing.JButton();
        viewFundsJButton = new javax.swing.JButton();

        financeTeamWorkAreaJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        financeTeamWorkAreaJLabel.setText("Finance Team Work Area");

        requestAccountJButton.setText("Request Money Transfer Account for Recepient");
        requestAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestAccountJButtonActionPerformed(evt);
            }
        });

        transferAmountJButton.setText("Transfer Amount to Recepient");
        transferAmountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferAmountJButtonActionPerformed(evt);
            }
        });

        viewDonationsJButton.setText("View Donations");
        viewDonationsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDonationsJButtonActionPerformed(evt);
            }
        });

        viewFundsJButton.setText("View Available funds");
        viewFundsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFundsJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(financeTeamWorkAreaJLabel)
                    .addComponent(transferAmountJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(requestAccountJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewDonationsJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewFundsJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(financeTeamWorkAreaJLabel)
                .addGap(50, 50, 50)
                .addComponent(requestAccountJButton)
                .addGap(35, 35, 35)
                .addComponent(transferAmountJButton)
                .addGap(35, 35, 35)
                .addComponent(viewDonationsJButton)
                .addGap(35, 35, 35)
                .addComponent(viewFundsJButton)
                .addContainerGap(255, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestAccountJButtonActionPerformed
        // TODO add your handling code here:
        RequestMoneyTransferAccountJPanel requestMoneyTransferAccountJPanel = new RequestMoneyTransferAccountJPanel(
                userProcessContainer,enterprise,organization,userAccount,system);
        userProcessContainer.add("RequestMoneyTransferAccountJPanel", requestMoneyTransferAccountJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestAccountJButtonActionPerformed

    private void transferAmountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferAmountJButtonActionPerformed
        // TODO add your handling code here:
        TransferMoneyJPanel transferMoneyJPanel = new TransferMoneyJPanel(userProcessContainer,
                enterprise,organization,userAccount,system);
        userProcessContainer.add("TransferMoneyJPanel", transferMoneyJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_transferAmountJButtonActionPerformed

    private void viewDonationsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDonationsJButtonActionPerformed
        // TODO add your handling code here:
        ViewDonationsJPanel viewDonationsJPanel = new ViewDonationsJPanel(userProcessContainer,(GiveDirectlyEnterprise)enterprise);
        userProcessContainer.add("ViewFundsJPanel", viewDonationsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewDonationsJButtonActionPerformed

    private void viewFundsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFundsJButtonActionPerformed
        // TODO add your handling code here:
        ViewAvailableFundsJPanel viewFundsJPanel = new ViewAvailableFundsJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("ViewFundsJPanel", viewFundsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewFundsJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel financeTeamWorkAreaJLabel;
    private javax.swing.JButton requestAccountJButton;
    private javax.swing.JButton transferAmountJButton;
    private javax.swing.JButton viewDonationsJButton;
    private javax.swing.JButton viewFundsJButton;
    // End of variables declaration//GEN-END:variables
}
