/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GiveDirectly.FinanceTeamRole;

import Business.Enterprise.Enterprise;
import Business.GiveDirectly.FinanceAccount;
import Business.GiveDirectly.FinanceTransaction;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Amey
 */
public class ViewAvailableFundsJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    /**
     * Creates new form ViewAvailableFundsJPanel
     */
    public ViewAvailableFundsJPanel(JPanel userJPanel,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userJPanel;
        this.enterprise = enterprise;
        populateFundDetails();;
    }
    
    private void populateFundDetails(){
        FinanceAccount financeAccount = FinanceAccount.getInstance();
        accountNameJTextField.setText(financeAccount.getAccountName());
        timeStampJTextField.setText(String.valueOf(financeAccount.getTimestamp()));
        
        double sum = 0.0;
        
        for(FinanceTransaction financeTransaction : financeAccount.getFinanceTransactionDirectory().getFinanceTransactionList())
        {
            sum+= financeTransaction.getAmount();
        }
        
        balanceJTextField.setText(String.valueOf(sum - financeAccount.getAmountConsumed()));
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewFundsJLabel = new javax.swing.JLabel();
        accountNameJLabel = new javax.swing.JLabel();
        timeStampJLabel = new javax.swing.JLabel();
        accountNameJTextField = new javax.swing.JTextField();
        timeStampJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        balanceJLabel = new javax.swing.JLabel();
        balanceJTextField = new javax.swing.JTextField();

        viewFundsJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewFundsJLabel.setText("View Available Funds");

        accountNameJLabel.setText("Account Name");

        timeStampJLabel.setText("Time stamp");

        accountNameJTextField.setEditable(false);

        timeStampJTextField.setEditable(false);

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        balanceJLabel.setText("Balance");

        balanceJTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(viewFundsJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(backJButton)))
                .addGap(377, 377, 377))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(balanceJLabel)
                    .addComponent(accountNameJLabel)
                    .addComponent(timeStampJLabel))
                .addGap(244, 244, 244)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(accountNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(timeStampJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(balanceJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(viewFundsJLabel)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(accountNameJLabel)
                    .addComponent(accountNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeStampJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeStampJLabel))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceJLabel)
                    .addComponent(balanceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(backJButton)
                .addGap(218, 218, 218))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNameJLabel;
    private javax.swing.JTextField accountNameJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel balanceJLabel;
    private javax.swing.JTextField balanceJTextField;
    private javax.swing.JLabel timeStampJLabel;
    private javax.swing.JTextField timeStampJTextField;
    private javax.swing.JLabel viewFundsJLabel;
    // End of variables declaration//GEN-END:variables
}
