/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GiveDirectly.FinanceTeamRole;

import Business.Enterprise.GiveDirectlyEnterprise;
import Business.Transaction.Transaction;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amey
 */
public class ViewDonationsJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private GiveDirectlyEnterprise giveDirectlyEnterprise;
    /**
     * Creates new form ViewFundsJPanel
     */
    public ViewDonationsJPanel(JPanel userJPanel, GiveDirectlyEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userJPanel;
        this.giveDirectlyEnterprise = enterprise;
        populateFunds();
        displayTotalFunds();
    }
    
    private void populateFunds(){
        DefaultTableModel model = (DefaultTableModel)fundsAvailableJTable.getModel();
        model.setRowCount(0);
        System.out.println("Transaction Directory: "+giveDirectlyEnterprise.getTransactionDirectory());
        System.out.println("List of transation:"+giveDirectlyEnterprise.getTransactionDirectory().getTransactionList());
        for(Transaction transaction:giveDirectlyEnterprise.getTransactionDirectory().getTransactionList()){
            Object[] object = new Object[3];
            object[0] = transaction.getTransactionID();
            object[1] = transaction.getSender().getFirstName();
            object[2] = transaction.getAmount();
            model.addRow(object);
        }
    }
    
    private void displayTotalFunds(){
        float totalFunds = 0;
        for(Transaction transaction:giveDirectlyEnterprise.getTransactionDirectory().getTransactionList()){
            totalFunds += transaction.getAmount();
        }
        System.out.println("Total funds are: "+totalFunds);
        totalDonationsJTextField.setText(String.valueOf(totalFunds));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewFundsJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fundsAvailableJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        totalDonationsJTextField = new javax.swing.JTextField();
        totalDonationsJLabel = new javax.swing.JLabel();

        viewFundsJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewFundsJLabel.setText("View Available Funds");

        fundsAvailableJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tran ID", "Donor", "Amount donated"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(fundsAvailableJTable);

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        totalDonationsJTextField.setEditable(false);
        totalDonationsJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalDonationsJTextFieldActionPerformed(evt);
            }
        });

        totalDonationsJLabel.setText("Total Donations");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewFundsJLabel)
                        .addGap(375, 375, 375))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(245, 245, 245))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(totalDonationsJLabel)
                        .addGap(185, 185, 185)
                        .addComponent(totalDonationsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(275, 275, 275))))
            .addGroup(layout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addComponent(backJButton)
                .addGap(448, 448, 448))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(viewFundsJLabel)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(totalDonationsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(totalDonationsJLabel))
                .addGap(50, 50, 50)
                .addComponent(backJButton)
                .addGap(236, 236, 236))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void totalDonationsJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalDonationsJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalDonationsJTextFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTable fundsAvailableJTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel totalDonationsJLabel;
    private javax.swing.JTextField totalDonationsJTextField;
    private javax.swing.JLabel viewFundsJLabel;
    // End of variables declaration//GEN-END:variables
}
