/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GiveDirectly.SupervisorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Amey
 */
public class SupervisorJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Organization organization;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private EcoSystem system;
    /**
     * Creates new form SupervisorJPanel
     */
    public SupervisorJPanel(JPanel userJPanel, Enterprise enterprise, 
            Organization organization,UserAccount account,EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userJPanel;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = account;
        this.system = ecoSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        supervisorWorkAreaJLabel = new javax.swing.JLabel();
        valiadetRecepientJButton = new javax.swing.JButton();

        supervisorWorkAreaJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        supervisorWorkAreaJLabel.setText("Supervisor Work Area");

        valiadetRecepientJButton.setText("Validate Recepient");
        valiadetRecepientJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valiadetRecepientJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(supervisorWorkAreaJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(valiadetRecepientJButton)))
                .addContainerGap(374, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(supervisorWorkAreaJLabel)
                .addGap(43, 43, 43)
                .addComponent(valiadetRecepientJButton)
                .addContainerGap(444, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void valiadetRecepientJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valiadetRecepientJButtonActionPerformed
        // TODO add your handling code here:
        ValidateRecepientJPanel validateRecepientJPanel = new ValidateRecepientJPanel(
                userProcessContainer,enterprise,userAccount,system);
        userProcessContainer.add("ValidateRecepientJPanel", validateRecepientJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_valiadetRecepientJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel supervisorWorkAreaJLabel;
    private javax.swing.JButton valiadetRecepientJButton;
    // End of variables declaration//GEN-END:variables
}
