/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GiveDirectly.FieldTeamRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Amey
 */
public class FieldTeamJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Organization organization;
    private UserAccount userAccount;
    private Enterprise enterprise;
    /**
     * Creates new form FieldTeamJPanel
     */
    public FieldTeamJPanel(JPanel userJPanel, Enterprise enterprise,
            Organization organization, UserAccount account) {
        initComponents();
        this.userProcessContainer = userJPanel;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldTeamWorkAreaJLabel = new javax.swing.JLabel();
        managePersonDataJButton = new javax.swing.JButton();
        requestApprovalJButton = new javax.swing.JButton();
        recepientDetailsJButton = new javax.swing.JButton();

        fieldTeamWorkAreaJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fieldTeamWorkAreaJLabel.setText("Field Team Work Area");

        managePersonDataJButton.setText("Manage Person Data");
        managePersonDataJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePersonDataJButtonActionPerformed(evt);
            }
        });

        requestApprovalJButton.setText("Request Approval");
        requestApprovalJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestApprovalJButtonActionPerformed(evt);
            }
        });

        recepientDetailsJButton.setText("View Recepient Details");
        recepientDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recepientDetailsJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(fieldTeamWorkAreaJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(managePersonDataJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(requestApprovalJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(recepientDetailsJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(374, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(fieldTeamWorkAreaJLabel)
                .addGap(45, 45, 45)
                .addComponent(managePersonDataJButton)
                .addGap(40, 40, 40)
                .addComponent(requestApprovalJButton)
                .addGap(40, 40, 40)
                .addComponent(recepientDetailsJButton)
                .addContainerGap(311, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void managePersonDataJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePersonDataJButtonActionPerformed
        // TODO add your handling code here:
        ManagePersonDataJPanel managePersonDataJPanel= new ManagePersonDataJPanel(
                userProcessContainer,enterprise,userAccount,organization);
        userProcessContainer.add("ManagePersonDataJPanel", managePersonDataJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePersonDataJButtonActionPerformed

    private void requestApprovalJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestApprovalJButtonActionPerformed
        // TODO add your handling code here:
        RequestApprovalJPanel requestApprovalJPanel= new RequestApprovalJPanel(
                userProcessContainer,enterprise,userAccount,organization);
        userProcessContainer.add("RequestApprovalJPanel", requestApprovalJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestApprovalJButtonActionPerformed

    private void recepientDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recepientDetailsJButtonActionPerformed
        // TODO add your handling code here:
        ViewRecepientDetailsJPanel viewRecepientDetailsJPanel = new ViewRecepientDetailsJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("ViewRecepientDetailsJPanel", viewRecepientDetailsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_recepientDetailsJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fieldTeamWorkAreaJLabel;
    private javax.swing.JButton managePersonDataJButton;
    private javax.swing.JButton recepientDetailsJButton;
    private javax.swing.JButton requestApprovalJButton;
    // End of variables declaration//GEN-END:variables
}
