/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GiveDirectly.FieldTeamRole;

import Business.Enterprise.Enterprise;
import Business.Organization.GiveDirectly.RecepientOrganization;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.Person.Recepient;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amey
 */
public class ViewRecepientDetailsJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    /**
     * Creates new form ViewRecepientDetailsJPanel
     */
    public ViewRecepientDetailsJPanel(JPanel userJPanel,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userJPanel;
        this.enterprise = enterprise;
        populateRecepientDetails();
    }

    private void populateRecepientDetails(){
        Organization organization = null;
        DefaultTableModel model = (DefaultTableModel)recepientDataJTable.getModel();
        model.setRowCount(0);
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(org instanceof RecepientOrganization){
                organization = org;
                for(Person person : org.getPersonDirectory().getPersonList()){
                    Recepient recepient = (Recepient)person;
                    Object[] object = new Object[7];
                    object[0] = recepient.getFirstName();
                    object[1] = recepient.getLastName();
                    object[2] = recepient.getNationalId();
                    object[3] = recepient.getCountry();
                    object[4] = recepient.getRegion();
                    object[5] = recepient.getAddress();
                    object[6] = recepient.getIncome();
                    model.addRow(object);
                }
            }  
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewRecepientJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recepientDataJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();

        viewRecepientJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewRecepientJLabel.setText("View Recepient Details");

        recepientDataJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "National ID", "Country", "Region", "Address", "Income"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(recepientDataJTable);

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewRecepientJLabel)
                        .addGap(367, 367, 367))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
            .addGroup(layout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addComponent(backJButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(viewRecepientJLabel)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(backJButton)
                .addContainerGap(317, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable recepientDataJTable;
    private javax.swing.JLabel viewRecepientJLabel;
    // End of variables declaration//GEN-END:variables
}
