/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Government.AdminRole;

import Business.Organization.Government.GovernmentEmployeeOrganization;
import Business.Person.Person;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Person.GovernmentEmployee;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amey
 */
public class ManagePersonJPanel extends javax.swing.JPanel {

    private OrganizationDirectory organizationDir;
    private JPanel userProcessContainer;
    private static final String EMAIL_PATTERN = 
    "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
    + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManagePersonJPanel(JPanel userProcessContainer,OrganizationDirectory organizationDir) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDir = organizationDir;
        
        populateOrganizationComboBox();
        populateOrganizationEmpComboBox();
    }
    
    public void populateOrganizationComboBox(){
        organizationJComboBox.removeAllItems();
        
        for (Organization organization : organizationDir.getOrganizationList()){
            organizationJComboBox.addItem(organization);
        }
    }
    
    public void populateOrganizationEmpComboBox(){
        organizationEmpJComboBox.removeAllItems();
        
        for (Organization organization : organizationDir.getOrganizationList()){
            organizationEmpJComboBox.addItem(organization);
        }
    }

    private void populateTable(Organization organization){
        DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();
        
        model.setRowCount(0);
        
        for (Person person : organization.getPersonDirectory().getPersonList()){
            Object[] row = new Object[2];
            row[0] = person.getId();
            row[1] = person.getFirstName();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        addJButton = new javax.swing.JButton();
        organizationJComboBox = new javax.swing.JComboBox();
        organizationJLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        firstNameJLabel = new javax.swing.JLabel();
        firstNameJTextField = new javax.swing.JTextField();
        organizationEmpJComboBox = new javax.swing.JComboBox();
        popUpOrganizationJLabel = new javax.swing.JLabel();
        managePersonJLabel = new javax.swing.JLabel();
        addressJLabel = new javax.swing.JLabel();
        phoneNumberJLabel = new javax.swing.JLabel();
        genderJLabel = new javax.swing.JLabel();
        emailIdJLabel = new javax.swing.JLabel();
        lastNameJLabel = new javax.swing.JLabel();
        pincodeJLabel = new javax.swing.JLabel();
        ageJLabel = new javax.swing.JLabel();
        lastNameJTextField = new javax.swing.JTextField();
        maleJRadioButton = new javax.swing.JRadioButton();
        femaleJRadioButton = new javax.swing.JRadioButton();
        ageJTextField = new javax.swing.JTextField();
        addressJTextField = new javax.swing.JTextField();
        pinCodeJTextField = new javax.swing.JTextField();
        emailIdJTextField = new javax.swing.JTextField();
        phoneNumberJTextField = new javax.swing.JTextField();

        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationJTable);
        if (organizationJTable.getColumnModel().getColumnCount() > 0) {
            organizationJTable.getColumnModel().getColumn(0).setResizable(false);
            organizationJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        addJButton.setText("Create Person");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBoxActionPerformed(evt);
            }
        });

        organizationJLabel.setText("Organization");

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        firstNameJLabel.setText("First Name");

        popUpOrganizationJLabel.setText("Organization");

        managePersonJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        managePersonJLabel.setText("Manage Person");

        addressJLabel.setText("Address");

        phoneNumberJLabel.setText("Phone Number");

        genderJLabel.setText("Gender");

        emailIdJLabel.setText("Email ID");

        lastNameJLabel.setText("Last Name");

        pincodeJLabel.setText("Pincode");

        ageJLabel.setText("Age");

        maleJRadioButton.setText("Male");

        femaleJRadioButton.setText("Female");

        ageJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageJTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageJTextFieldKeyTyped(evt);
            }
        });

        pinCodeJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pinCodeJTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pinCodeJTextFieldKeyTyped(evt);
            }
        });

        phoneNumberJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneNumberJTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNumberJTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(popUpOrganizationJLabel)
                            .addComponent(firstNameJLabel)
                            .addComponent(ageJLabel)
                            .addComponent(addressJLabel)
                            .addComponent(pincodeJLabel)
                            .addComponent(emailIdJLabel)
                            .addComponent(phoneNumberJLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameJLabel)
                            .addComponent(genderJLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(organizationJLabel)
                        .addGap(134, 134, 134)
                        .addComponent(organizationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(managePersonJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(backJButton)
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(organizationEmpJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addJButton)
                            .addComponent(firstNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pinCodeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(maleJRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(femaleJRadioButton))
                                .addComponent(ageJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(managePersonJLabel)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizationJLabel)
                    .addComponent(organizationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizationEmpJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(popUpOrganizationJLabel))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameJLabel)
                    .addComponent(firstNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameJLabel))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderJLabel)
                    .addComponent(maleJRadioButton)
                    .addComponent(femaleJRadioButton))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageJLabel)
                    .addComponent(ageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressJLabel)
                    .addComponent(addressJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pincodeJLabel)
                    .addComponent(pinCodeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailIdJLabel)
                    .addComponent(emailIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberJLabel)
                    .addComponent(phoneNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(addJButton))
                .addGap(66, 66, 66))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        if (firstNameJTextField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the name!!!");
            firstNameJTextField.setText("");
            firstNameJTextField.requestFocus();
        }
        else if (lastNameJTextField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null,"Please enter the Last Name!!!");
            lastNameJTextField.setText("");
            lastNameJTextField.requestFocus();
        }
        else if((maleJRadioButton.isSelected() == false) &&
                (femaleJRadioButton.isSelected() == false) ){
            JOptionPane.showMessageDialog(null, "Please select the gender!!!");
        } 
        else if (ageJTextField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the Age!!!");
            ageJTextField.setText("");
            ageJTextField.requestFocus();
        }
        else if (addressJTextField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the Address!!!");
            addressJTextField.setText("");
            addressJTextField.requestFocus();
        }
        else if (pinCodeJTextField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the Pin Code!!!");
            pinCodeJTextField.setText("");
            pinCodeJTextField.requestFocus();
        }
        else if (emailIdJTextField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the Email ID!!!");
            emailIdJTextField.setText("");
            emailIdJTextField.requestFocus();
        }
        else if (phoneNumberJTextField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null,"Please enter the Phone !!!");
            phoneNumberJTextField.setText("");
            phoneNumberJTextField.requestFocus();
        }
        else if(!(emailIdJTextField.getText().matches(EMAIL_PATTERN))){
            JOptionPane.showMessageDialog(null, "Please enter valid Email ID!");
            emailIdJTextField.setText("");
            emailIdJTextField.requestFocus();
        }
        else{
            try{
                Organization organization = (Organization) organizationEmpJComboBox.getSelectedItem();
                String gender = null;
                if(maleJRadioButton.isSelected()){
                    gender = "Male";
                }
                else{
                    gender = "Female";
                }
                if(organization instanceof GovernmentEmployeeOrganization){
                    GovernmentEmployee governmentEmployee = new GovernmentEmployee();
                    governmentEmployee.setFirstName(firstNameJTextField.getText().trim());
                    governmentEmployee.setLastName(lastNameJTextField.getText().trim());
                    governmentEmployee.setGender(gender);
                    governmentEmployee.setAge(Integer.parseInt(ageJTextField.getText().trim()));
                    governmentEmployee.setAddress(addressJTextField.getText().trim());
                    governmentEmployee.setPincode(Integer.parseInt(pinCodeJTextField.getText().trim()));
                    governmentEmployee.setEmailId(emailIdJTextField.getText().trim());
                    governmentEmployee.setPhoneNumber(Float.parseFloat(phoneNumberJTextField.getText()));
                    organization.getPersonDirectory().getPersonList().add(governmentEmployee);
                    JOptionPane.showMessageDialog(null, "Government Employee created successfully!!!");
                }
                else{
                    String name = firstNameJTextField.getText().trim();
                    organization.getPersonDirectory().createPerson(name);   
                    JOptionPane.showMessageDialog(null, "Person created successfully!!!");
                }            
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,
                        "Please insert valid number value!!!");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,
                    "There's some error with database,please try again later!!");
            }
        }
    }//GEN-LAST:event_addJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed
        Organization organization = (Organization) organizationJComboBox.getSelectedItem();
        if (organization != null){
            populateTable(organization);
        }
    }//GEN-LAST:event_organizationJComboBoxActionPerformed

    private void ageJTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageJTextFieldKeyPressed
        // TODO add your handling code here:
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_C) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot copy code from this field!!!");
        }
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_X) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot cut code from this field!!!");
        }
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_V) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot paste code into this field!!!");
        }
    }//GEN-LAST:event_ageJTextFieldKeyPressed

    private void ageJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageJTextFieldKeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        int length = ageJTextField.getText().length();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)
            || length >= 3){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_ageJTextFieldKeyTyped

    private void pinCodeJTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinCodeJTextFieldKeyPressed
        // TODO add your handling code here:
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_C) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot copy code from this field!!!");
        }
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_X) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot cut code from this field!!!");
        }
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_V) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot paste code into this field!!!");
        }
    }//GEN-LAST:event_pinCodeJTextFieldKeyPressed

    private void pinCodeJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinCodeJTextFieldKeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        int length = pinCodeJTextField.getText().length();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)
            || length>=5){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_pinCodeJTextFieldKeyTyped

    private void phoneNumberJTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberJTextFieldKeyPressed
        // TODO add your handling code here:
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_C) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot copy code from this field!!!");
        }
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_X) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot cut code from this field!!!");
        }
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_V) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You cannot paste code into this field!!!");
        }
    }//GEN-LAST:event_phoneNumberJTextFieldKeyPressed

    private void phoneNumberJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberJTextFieldKeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();
        int length = phoneNumberJTextField.getText().length();
        if(!(Character.isDigit(character) || character == KeyEvent.VK_BACK_SPACE || character == KeyEvent.VK_DELETE)
            || length>=10){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_phoneNumberJTextFieldKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JLabel addressJLabel;
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JLabel ageJLabel;
    private javax.swing.JTextField ageJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel emailIdJLabel;
    private javax.swing.JTextField emailIdJTextField;
    private javax.swing.JRadioButton femaleJRadioButton;
    private javax.swing.JLabel firstNameJLabel;
    private javax.swing.JTextField firstNameJTextField;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel genderJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameJLabel;
    private javax.swing.JTextField lastNameJTextField;
    private javax.swing.JRadioButton maleJRadioButton;
    private javax.swing.JLabel managePersonJLabel;
    private javax.swing.JComboBox organizationEmpJComboBox;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JLabel organizationJLabel;
    private javax.swing.JTable organizationJTable;
    private javax.swing.JLabel phoneNumberJLabel;
    private javax.swing.JTextField phoneNumberJTextField;
    private javax.swing.JTextField pinCodeJTextField;
    private javax.swing.JLabel pincodeJLabel;
    private javax.swing.JLabel popUpOrganizationJLabel;
    // End of variables declaration//GEN-END:variables
}
